import type { ModelConfig } from 'openfox/provider'

export function getDefaultModels(): ModelConfig[] {
  return [
    { id: 'gpt-5.6-sol', name: 'GPT-5.6 Sol', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.6-terra', name: 'GPT-5.6 Terra', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.4', name: 'GPT-5.4', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.4-pro', name: 'GPT-5.4 Pro', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.4-mini', name: 'GPT-5.4 Mini', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.3-codex', name: 'GPT-5.3 Codex', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.3-codex-spark', name: 'GPT-5.3 Codex Spark', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.2', name: 'GPT-5.2', contextWindow: 200000, source: 'default' },
    { id: 'gpt-5.2-codex', name: 'GPT-5.2 Codex', contextWindow: 200000, source: 'default' },
    { id: 'gpt-4o', name: 'GPT-4o', contextWindow: 128000, source: 'default' },
    { id: 'gpt-4o-mini', name: 'GPT-4o Mini', contextWindow: 128000, source: 'default' },
    { id: 'o1', name: 'o1', contextWindow: 200000, source: 'default' },
    { id: 'o3-mini', name: 'o3-mini', contextWindow: 200000, source: 'default' },
    { id: 'claude-sonnet-4.6', name: 'Claude Sonnet 4.6', contextWindow: 200000, source: 'default' },
    { id: 'claude-sonnet-4.5', name: 'Claude Sonnet 4.5', contextWindow: 200000, source: 'default' },
    { id: 'claude-sonnet-4', name: 'Claude Sonnet 4', contextWindow: 200000, source: 'default' },
    { id: 'claude-sonnet-5', name: 'Claude Sonnet 5', contextWindow: 200000, source: 'default' },
    { id: 'claude-opus-4.8', name: 'Claude Opus 4.8', contextWindow: 200000, source: 'default' },
    { id: 'claude-opus-4.7', name: 'Claude Opus 4.7', contextWindow: 200000, source: 'default' },
    { id: 'claude-opus-4.6', name: 'Claude Opus 4.6', contextWindow: 200000, source: 'default' },
    { id: 'claude-opus-4.5', name: 'Claude Opus 4.5', contextWindow: 200000, source: 'default' },
    { id: 'claude-haiku-4.5', name: 'Claude Haiku 4.5', contextWindow: 200000, source: 'default' },
    { id: 'claude-fable-5', name: 'Claude Fable 5', contextWindow: 200000, source: 'default' },
    { id: 'gemini-2.5-pro', name: 'Gemini 2.5 Pro', contextWindow: 1000000, source: 'default' },
    { id: 'gemini-2.5-flash', name: 'Gemini 2.5 Flash', contextWindow: 1000000, source: 'default' },
    { id: 'deepseek-r1', name: 'DeepSeek R1', contextWindow: 128000, source: 'default' },
    { id: 'deepseek-v3-0324', name: 'DeepSeek V3', contextWindow: 128000, source: 'default' },
    { id: 'kimi-k2.7-code', name: 'Kimi K2.7 Code', contextWindow: 128000, source: 'default' },
    { id: 'mistral-small-2503', name: 'Mistral Small', contextWindow: 128000, source: 'default' },
  ]
}
